sudo: required
language: scala
jdk:
- openjdk8
services:
- docker

env:
  global:
  # AWS_ACCESS_KEY_ID
  - secure: "PKS9hx8wnTWmDvblB3ZnKSIAIm3Yn0EA6PoynaiUj2WnwPLa8oP0Tosgw8ySfxLG9bfobCPHCd5N378C4B/TWfdfUTKMn7xqb2xZbWkkPMa7rvlaKw/HGtykT5rCNqg1znlXATyi2d1HZgTJChYS30vzo3eIzrLjqAaM/ZT01LlWWjSu0YsDITRnzR+S39eSKOeGihIJ98xDHpMfz8sHs+9ktjOJl6G1Pa2IkyJheXSGb4eI6byqtTtiZTc2WgQfo4tLcxhi6Pmz9j2H+E78nQogSCuQufEBldClE9v10C8gXzzOI7gfmNmUCdbrlN9kC3jVdFKNy47xBJcSdXEovtbOL9eFfY+G/9+5hIYTrvCnVyOiGj5xiCD0KqFDoZSTv1xdSDeHodzTgByc7GAoyurwPO4yr8U+kh4/1ouk9euM7S9fFidBgp2hJny0Vrm2MQNuT3jB51zx5Hbv5CFesSALlxWIBo/gtZxcL4dpQSfMOLNn/18HC3w/7lwQXE4vA5oBPX4SDOe9BQN0iYdqAqLgcBitFZMltGv7OLrkebX3+uYEDaXttu/Ivv6+MN1KJnLREBIWKBdURbPcjKhm73jcyj21yw+dddsIx9UDf13vtPRq6r4ZaD/7tNeirMZ40aLiZ3Tg2NsaU4c9HmHg3a9aeGfmn/tjrmVTLu2xye0="
  # AWS_SECRET_ACCESS_KEY
  - secure: "BWkY3fwmOpYoEzxZLEpALwQOrKnHePTmwDvxMQGyO0Db7WT2UXo8BRDunLOmPiUfOgAlA1fEvdSz2uOOilzC9EFFgmMdX8SZjp45NF6OGy1zJSV11kbxMoGXcEAeo9i6X+SAG+0EV3zYLfU8Aen8zv++GmgmEFRuy0q/GbpfK0JbT+9zpVvsa4jTIadHXwcvAEtfJWmtnoufSGY67+1QTeQvu3b+vbgER1xT9Bs4kxad8WiuUOSOJDIIj21EIWlKkEG2M4cg++6h6qFVkl4PTG1GF5ejKhimd4xCsziLKSn014twqH1Nt8GqwucsCqjBVEzsnUGP1pdXu1aUt/lx1PnYkN/XYz0z5axEPQBz2Op9Oun4WeOf5mXF0xUBkwCE15P6M7cYqi6uXlPqel/Vg/9ax/ibYRrknXGxaQH7j065Hc1emwPAuIdcA63SBDaTxCt385Xas8yMHL4QQi0QBesnW2w1igxCW/7fV6q/RAIUi2c/LD+OUAsI6trrvcQnRvF0u0wg/CQTuMdCR+XGPchD59AOSeRVhpMy3v0y1H5a1qM3OXZfeG9U1PKDHCts/nj3DmxriEadjvr+Po+j+16uMZ0BjeyUrLBiMZDv9DgGgtCrpsuJWnOpoNebcODHULkSlTdsENQOtUeiNq1tuiGlOD9lzcP2nq9hQg0CYZU="

install:
- git clone https://github.com/Opetushallitus/ci-tools.git
- source ci-tools/common/setup-tools.sh
- export ARTIFACT_NAME="virkailijan-tyopoyta"

script:
- mvn clean install -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

- mv target/virkailijan-tyopoyta-*.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar
- cp -vr src/main/resources/* $DOCKER_BUILD_DIR/config/

- export BASE_IMAGE="baseimage-fatjar-openjdk8:master"
- ./ci-tools/common/pull-image.sh
- ./ci-tools/build/build-fatjar.sh $ARTIFACT_NAME

deploy:
  provider: script
  script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
  on:
    all_branches: true